### PR TITLE
Fix TypeError: require(...) is not a function

### LINKED ISSUE #29: TypeError: require(...) is not a function
Hi, I have this issue, I hope you can help me. 
This problem is very curious since it was presented 2 days ago after deleting node_module and reinstalling the packages (I do not update any version packages or node), I describe:

App.jsx 
```
import 'react-table/react-table.css'
```

webpack.config.js
```
module:{
    rules:[
      ...
      {
        test: /\.css$/,
        use: [
          'style-loader/url',
          'url-loader?limit=10000',
          'extract-loader',
          'css-loader?root=' + path.resolve(__dirname, 'assets')
        ]
      }
   ]
}
```

command 
```
npm run dev-server
```

Result
```
10% building modules 1/1 modules 0 active
Project is running at http://0.0.0.0:8081/
  webpack output is served from /
Content not from webpack is served from ./build
404s will fallback to /index.html                                                
Hash: 50cfb73d68cbc86989c2
Version: webpack 3.10.0
Time: 27055ms
Asset       Size  Chunks                    Chunk Names
0.bundle.js    1.71 MB       0  [emitted]  [big]
1.bundle.js    1.51 MB       1  [emitted]  [big]
2.bundle.js     936 kB       2  [emitted]  [big]
bundle.js    3.95 MB       3  [emitted]  [big]  main
0.bundle.js.map    1.66 MB       0  [emitted]
1.bundle.js.map    1.56 MB       1  [emitted]
2.bundle.js.map    1.02 MB       2  [emitted]
bundle.js.map    4.51 MB       3  [emitted]         main
index.html  484 bytes          [emitted]
  [1] ./node_modules/react/index.js 190 bytes {3} [built]
  [276] ./node_modules/react-router-redux/es/index.js 420 bytes {3} [built]
  [277] ./node_modules/react-router-dom/es/index.js 925 bytes {3} [built]
  [282] ./theme/index.js 5.99 kB {3} [built]
  [297] ./node_modules/url/url.js 23.3 kB {3} [built]
  [366] ./node_modules/material-ui/styles/getMuiTheme.js 13.1 kB {3} [built]
  [510] multi (webpack)-dev-server/client?http://0.0.0.0:8081 babel-polyfill ./app.jsx 52 bytes {3} [built]
  [511] (webpack)-dev-server/client?http://0.0.0.0:8081 7.63 kB {3} [built]
    [531] ./node_modules/babel-polyfill/lib/index.js 833 bytes {3} [built]
  [733] ./app.jsx 8.7 kB {3} [built]
  [821] ./node_modules/material-ui/styles/MuiThemeProvider.js 2.14 kB {3} [built]
  [847] ./node_modules/react-x-ray/dist/XRay.js 2.08 kB {3} [built]
  [1268] ./node_modules/react-table/react-table.css 847 bytes {3} [built]
  [1271] ./modules/index.js 5.98 kB {3} [built]
  [1273] ./node_modules/url-loader!./assets/images/logo/blue.png 20.3 kB {3} [built]
+ 1662 hidden modules

ERROR in ./node_modules/url-loader?limit=10000!./node_modules/extract-loader/lib/extractLoader.js!./node_modules/css-loader?root=/Users/mymachine/Documents/myproject/assets!./node_modules/react-table/react-table.css
Module build failed: /Users/mymachine/Documents/myproject/node_modules/react-table/react-table.css:1
exports = module.exports = require("../css-loader/lib/css-base.js")(false);
                                                                   ^

TypeError: require(...) is not a function
at /Users/mymachine/Documents/myproject/node_modules/react-table/react-table.css:1:68
at Script.runInContext (vm.js:74:29)
at Script.runInNewContext (vm.js:80:15)
at Object.extractLoader (/Users/mymachine/Documents/myproject/node_modules/extract-loader/lib/extractLoader.js:88:12)
@ ./node_modules/react-table/react-table.css 3:1-184
@ ./app.jsx
@ multi (webpack)-dev-server/client?http://0.0.0.0:8081 babel-polyfill ./app.jsx
  Child html-webpack-plugin for "index.html":
1 asset
  [0] ./node_modules/html-webpack-plugin/lib/loader.js!./index.html 795 bytes {0} [built]
  [1] ./node_modules/lodash/lodash.js 540 kB {0} [built]
  [2] (webpack)/buildin/global.js 509 bytes {0} [built]
  [3] (webpack)/buildin/module.js 517 bytes {0} [built]
webpack: Failed to compile.
```

Thanks for your help

### PR DESCRIPTION
**Pull request by benurb**
Should fix #29

### CODE REVIEW

**Comment by Anahkiasen** [comment]
Having the same issue on Webpack 4 and can confirm this fix works if I replicate it locally

**Comment by chrisfarms** [comment]
This resolves issues I was seeing to. 👍

**Comment by guoyongxin** [comment]
I got the same issue.
By restricted dependencies in package.json resolve my case.
```
{
 "css-loader": "0.28.9", 
 "extract-loader": "1.0.1"
}
```

**Comment by benurb** [comment]
Hi @guoyongxin,
this issue was resolved with extract-loader v2.0.0. If there is still a problem with the css-loader could you please open an issue with more information? Thanks!

**Pull request merged**
