### PR TITLE
feat: Add support for ECMAScript modules

### PR DESCRIPTION
**Pull request by cybercase**
Following the discussion #67 I've made some changes to add transpilation of es modules.
This should solve the issue with the new default behaviour of file-loader v.5 of enabling esModules by default.

Looking at how file-loader is implemented [here](https://github.com/webpack-contrib/file-loader/blob/master/src/index.js#L65), and agreeing with @carsonreinke, I would have opted for a simpler fix, like the one you received in #26 .
However, since you've expressed the preference of using babel to avoid risks, I've followed your preference.

Let me know if you're ok with this PR or if you need me to make further changes.

### CODE REVIEW

**Comment by cybercase** [comment]
After looking at the tests failing on node 6, I tried to find out what was wrong.
I debugged the issue to find out the cause, and unfortunately it's not related to this PR.

So, here's the problem.

In the _.babelrc_ of this project it's loaded the `babel-plugin-istanbul` plugin when _NODE_ENV_ is set to _test_.
Starting from version 5.1.0 of `babel-plugin-istanbul`, babel 7 is required for it to work properly, and starting from version 5.2.0 an error is thrown if babel 6 is used instead of babel 7; [here is](https://github.com/istanbuljs/babel-plugin-istanbul/pull/207) the PR where they've had the discussion and then added the version check.

Since in this project both package.json and package-lock.json refer to version 5.0.1 of that plugin, everything should work fine since we're bound to that version.

However, the npm version 3 that's coming with node 6 does not honor the package-lock.json file, and installs the latest version matching the semantic versioning of package.json, that is 5.2.0.

I can think of 2 possible fixes.
- Add a shrinkwrap file to make sure that even npm v.3 installs the correct version of `babel-plugin-istanbul`
- Change the semver string related to `babel-plugin-istanbul` to make sure it matches version only up to 5.1.X (maybe using `^5.0.1 < 5.0.X`)

By the way, this should probably be done in a separate PR.

Let me know what you think

**Comment by carsonreinke** [comment]
...or drop Node 6.  Is this still being used?  Isn't it EOL?

**Comment by cybercase** [comment]
@carsonreinke I also think that support for v6 could be dropped.

However, I'm not sure this PR will be reviewed soon. It's been almost a month since I've opened it, and haven't received any feedback. Do you know someone to mention who could help us in moving this forward?

**Comment by cybercase** [comment]
@jannikkeye @jhnns 
I've aligned this PR to master to resolve conflicts in `package-lock.json`.
Happy to see that node6 has been removed from travis ci and all checks are good now.

**Comment by carsonreinke** [comment]
@cybercase sorry for not getting back to you, for sure dropping Node 6.

My only thought about this too, this puts a dependency on Babel 6 for projects that use extract-loader.  What if I wanted to use Babel 7 in my project and use extract-loader?  I really don't see a way around that, unless some sort of peer dependency and Babel version check nonsense.

**Comment by cybercase** [comment]
@carsonreinke as I said in the first comment of this PR, I agree with you. I liked the approach of #26  that doesn't depend upon any babel version at all. However, following the discussion in that same PR, I read that the maintainer has a different point of view... that's why I choose to use babel in this PR.

**Comment by jhnns** [comment]
@cybercase Thanks ❤️ I will review this in this week.

**Comment by jhnns** [comment]
Awesome, thank you 👍

I decided to release it as major version bump because the usage of Babel might introduce unwanted/unknown side-effects in some project setups. I don't think that it's a problem but let's better be safe than sorry :)

**Pull request merged**
