### PR TITLE
#55 - Fix issue with loading resource with Query parameters, it doesn…

### PR DESCRIPTION
**Pull request by alqh**
…'t currently slice the path for query parameters

### CODE REVIEW

**Comment by alqh** [comment]
@jhnns  Would you be able to please review this PR and push through it to a version so that the bug fix can flow through?

**Comment by alqh** [comment]
The task that is failing on the build process is about the babel version that is loaded is 6.X whereas the babel version that it is expected is 7.X.. This look like a build job configuration, any chance we can get that fixed?

**Comment by jannikkeye** [comment]
Hi there @alqh,

thank you for your contribution. Excuse the late response. I modified your proposed changes to also work for cases where a resource path has explicit loaders and a query and added an additional test case. Regarding the CI error we decided to drop node 6 support.

Are these changes ok for you?

**Comment by alqh** [comment]
Hi @jannikkeye , thank you for picking up this PR. 

Your commit makes sense, I see the case where there are double-ups in the path and the iteration will just chop the last match one?

Looks good to me, please go ahead @jannikkeye .

Thank you.!

**Comment by alqh** [comment]
Thank you @jannikkeye  for your time and help!

**Comment by jhnns** [comment]
@alqh We switched to semantic-release but had some problems configuring it. Sorry for that 😞. We will release a fixed version today.

**Comment by jannikkeye** [comment]
@alqh Can you please install the latest version (should be 4.0.3). We fixed the semantic-release process so build assets are properly included  before publishing: https://unpkg.com/extract-loader@4.0.3/lib/extractLoader.js

**Comment by alqh** [comment]
@jannikkeye  Thank you. I've pulled them and tested across our projects. Its working good now. Thank you !!

**Comment by jannikkeye** [comment]
@alqh Glad to hear it. 🎉

**Pull request merged**
